### ISSUE TITLE
Hitboxes fucked up

### ISSUE THREAD

**Issue by SushiEater44** [bIinno/fpsgamefunny#1]
This update made the hitboxes go brrrrr. 

Version: **0.2.3 - Pre Release **
How to reproduce: Just shoot at a guy

pls fix, im a professional speedrunner and this update almost ruined the World Record (im the world record holder)

@bIinno

**Comment by bIinno** [comment]
**Hey,** @SushiEater44 

I'm sorry about the issue you are having with the hitboxes.
Unfortunately, I couldn't reproduce this bug at all.

If you are still having this issue,
Reply to this with clearer steps for reproducing.

**Thanks,**
@bIinno

**Comment by SushiEater44** [comment]
> **Hey,** @SushiEater44
> 
> I'm sorry about the issue you are having with the hitboxes.
> Unfortunately, I couldn't reproduce this bug at all.
> 
> If you are still having this issue,
> Reply to this with clearer steps for reproducing.
> 
> **Thanks,**
> @bIinno

Yea cause i fixed it
